language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - yarn test
before_deploy:
  - npm install netlify-cli -g
  - yarn build
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_AUTH_TOKEN -p -d ./dist
  skip_cleanup: true
  on:
    branch: main
